default:
  image: ghcr.io/foundry-rs/foundry:latest

variables:
  FOUNDRY_PROFILE: "ci"
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - check

check:
  stage: check
  rules:
    - if: $CI_COMMIT_BRANCH == "main" || $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - contracts/**/*
        - test/**/*
      when: on_success
    - when: never
  script:
    - forge --version
    - forge build --sizes
    - forge test -vvv
    - forge coverage
  coverage:  /Total\s([^\|]*\|\s+){2}(\d+.\d+)%/ # Total Statements (The last matching number is used.)
