default:
  image: ghcr.io/foundry-rs/foundry:latest
  before_script:
    - apk add --update npm
    - npm install

variables:
  FOUNDRY_PROFILE: "ci"
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - check

check:
  stage: check
  rules:
    - if: $CI_MERGE_REQUEST_TITLE =~ /^([\[\(]?(Draft|WIP)[\]\):])/
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: on_success
    - when: never
  script:
    - forge --version
    - forge build --sizes
    - forge test -vvv
